language: python
python:
  - "3.5"
#  - "pypy"
# command to install dependencies
install:
#  - pip install .
  - pip install -r requirements.txt
  - pip install codecov
# command to run tests
script: nosetests --with-coverage --cover-package=uitester
after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)