language: python
python:
  - "3.5"
#  - "pypy"
# command to install dependencies
install:
#  - pip install .
  - pip install -r requirements.txt
  - pip install codecov
# command to run tests
script:
  - codecov --token=f732ae6e-083a-43f6-ab25-74ce22121b3a
after_success:
  - codecov