language: python
python:
  - "3.5"
#  - "pypy"
# command to install dependencies
install:
#  - pip install .
  - pip install -r requirements.txt
  - pip install codecov
# command to run tests
script: nosetests
after_success:
  - codecov --token=813ed50d-d50e-44c9-9c75-5e171e925529